site_name: Document
copyright: "&copy; 2023-present TNCT-Mechatech"
repo_url: https://github.com/TNCT-Mechatech/Document
repo_name: TNCT-Mechatech/Document
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TNCT-Mechatech
nav:
  - ホーム:
      - index.md
  - 共通:
      - common/index.md
      - ページ追加方法: common/create-new-document/index.md
      - GitHub Desktop: common/github-desktop/index.md
      - Trello: common/trello/index.md
  - 機械:
      - mechanical/index.md
  - 回路:
      - circuit/index.md
  - 制御:
      - control/index.md
      - Mbed:
          - control/mbed/index.md
          - API:
              - control/mbed/api/index.md
              - Ticker: control/mbed/api/ticker/index.md
      - 通信:
          - control/communication/index.md
  - 教育:
      - education/index.md
theme:
  name: material
  language: ja
  features:
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "#"
